### ISSUE TITLE
Enhancement: Common init runner for all runners

### ISSUE THREAD

**Issue by sudhagarc** [max-au/erlperf#17]
I often use `erlperf` is used to compare the performance of multiple variants to choose the optimal one. In such instances, it would be convenient to have a common init runner that passes the data to all the variants, instead of duplicating `--init_runner` for each runner. 

Example:
Current invocation:
`erlperf 'run(A) -> mod:fun_1(A).' --init_runner 'mod:gen_data().' 'run(B) -> mod:fun_2(B).' --init_runner 'mod:gen_data().'`

Here `--init_runner 'mod:gen_data().'` block is repeated twice. Instead it would convenient to just pass it once, possibly using a new option?

Thoughts on the new option:
`erlperf 'run(A) -> mod:fun_1(A).' 'run(A) -> mod:fun_2(A).' --init_runner_all 'mod:gen_data().'`

**Comment by max-au** [comment]
Implemented in 2.0.2: https://github.com/max-au/erlperf/releases/tag/2.0.2
