### ISSUE TITLE
Report flag not working

### ISSUE THREAD

**Issue by Zabrane** [max-au/erlperf#45]
Hi @max-au 

I'm trying to get a detailed report by using `--report full` but this doesn't seem to extend the output result.
Always getting the same number of colons:
```
Code                             ||   Samples       Avg   StdDev    Median      P99  Iteration    Rel
```

Same when using  `--report extended`.

I'm currently testing with the latest `erlperf` from `master` (https://github.com/max-au/erlperf/commit/9237f008f02cfc6bd4b10d0b89367ece4b674396).

```bash
$ erl
Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [dtrace]

$ sw_vers
ProductName:		macOS
ProductVersion:		14.5

```

Help appreciated.
Thanks

**Comment by Zabrane** [comment]
@max-au never mind. What's the difference between `full` and `extended`? The columns are the same.

**Comment by max-au** [comment]
GDay, see the documentation: https://hexdocs.pm/erlperf/readme.html#full-report

Full report

This mode must be explicitly specified with -r full.

Contains everything that extended report has. Includes extra information about the system used for benchmarking - OS type, CPU and Erlang VM characteristics.

**Comment by Zabrane** [comment]
> GDay, see the documentation: https://hexdocs.pm/erlperf/readme.html#full-report
> 
> Full report
> 
> This mode must be explicitly specified with -r full.
> 
> Contains everything that extended report has. Includes extra information about the system used for benchmarking - OS type, CPU and Erlang VM characteristics.

Hello @max-au

I see. But what's the difference between `full` and `extended`?
I don't see any difference (same number of columns).

**Comment by max-au** [comment]
Columns are the same, but `full` report also contains extra (textual) information that is not part of the table - OS, CPU, Erlang VM characteristics. `extended` report should not print this.
